language: android

jdk:
 - oraclejdk7
 - oraclejdk8

matrix:
  allow_failures:
    - jdk: oraclejdk7

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
#    - android-23 # need to remove Apache deps
    - android-22
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - '.+'

script:
    - ./gradlew clean assemble --stacktrace

notifications:
  email: false

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

