language: android

jdk:
 - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
#    - android-23 # need to remove Apache deps
    - android-22
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - '.+'

script:
    - ./gradlew clean assemble --stacktrace

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle

