language: android

jdk:
 - oraclejdk7
 - oraclejdk8

matrix:
  allow_failures:
    - jdk: oraclejdk7

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
  licenses:
    - '.+'

script:
    - ./gradlew clean assemble --stacktrace

notifications:
  email: false

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
